[package]
name = "snaxum-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
snaxum = { path = ".." }
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pyo3 = { version = "0.27.2", features = ["auto-initialize"] }
tracing = "0.1"
tracing-subscriber = "0.3"
